Saving a slice of frames in a single operation, and removed fsync
go-audio/wav pull request #19
Opened 2019-04-28 21:50 UTC by ivoras

See commit descriptions and issue #18 for details.

2019-04-28 22:01 UTC, mattetti commented
Thanks a lot for the PR, I like the direction, I am a bit surprised that a frame is equal to a sample, that doesn't seem right in the case of a file with more than 1 channel (a frame is a sample * num channels).

I need to try to remember why I was syncing when setting up the metadata, it doesn't seem to make a lot of sense but I will try to dig through the history.

Finally, any chance you could add some tests to make sure the code behaves as expected, especially with the type of frames.

2019-04-29 12:24 UTC, ivoras commented
It was just a single sample in my case where I have a single channel. I handled the case with multiple channels partially - some checks are needed that the slice length is sane.

The original issue is just a side effect of Go's binary.Write() accepting both simple types (like integers) and slices of those, transparently.

I'll add the tests and submit another PR.

2020-09-07 06:02 UTC, shmsr commented on go.mod
> +module github.com/ivoras/wav
You shouldn't have included this change with this PR.

2020-09-07 06:27 UTC, mattetti requested changes

2020-09-07 06:27 UTC, mattetti commented on go.mod
> +module github.com/ivoras/wav
Should import go-audio/wav

2020-09-08 16:25 UTC, closed without merging